#2288 Enable currency setting (#2299)
* #2088 start beta (#2252)

* #2088 start beta

* #2088 release_notes.md update translations

* #2088 release_notes.md

* Ignore unwanted files

* #2256 Fix gradle github action (#2257)

* #2088 start beta

* #2088 release_notes.md update translations

* #2088 release_notes.md

* Ignore unwanted files

* #2256 gradle/actions/wrapper-validation@v3

* Update action to latest version

* Make `gradlew` executable.

* Upgrade gradle to latest 8.x version, make `gradlew` executable, and restore wrapper jar.

* #2258 Fix MatchFixtures.findReplacementOfTeam (#2261)

* #2262 Fix HOTableModel.getRowOrderSettings (#2263)

* #2262 Fix HOTableModel.getRowOrderSettings (#2264)

* #2265 Fix HOTableModel.moveColumn (#2266)

* #2255 New countries (#2268)

* Fix tactics ratings

* #2255 Add two new flags

* #2255 Fix PluginIfaUtils.getCoolness

* #2255 Fix PluginIfaUtils.getCoolness

* #2255 release_notes.md

* #2267 1 (#2269)

* Fix tactics ratings

* #2255 Add two new flags

* #2267 Fix Player.copySkills

* #2267 release_notes.md

* #2271 (#2272)

* #2271 Fix XMLPlayersParser.createPlayer

* #2271 relaease.notes

* #2270 Fix XtraDataTable.initColumns (#2273)

* tooltip in subskill editor (#2276)

* #2088 release stable 9.0 (#2279)

* #2284 Fix init of xtra data table  (#2285)

* empty release_notes.md

* #2284 Fix XtraData.getDailyUpdate

* #2284 release_notes.md

* #2286 Lineup handles red carded players (#2287)

* #2284 release_notes.md Fix link to detailed changelog

* #2286 Lineup handles red carded players

* #2286 remove unused method

* #2286 Fix MatchLineupTeam.initMinutesOfPlayersInSectors red carded players (#2289)

* #2288 Rename Greeklish to Greek

* #2288 Remove Languages.java

* #2288 Remove unused methods in DateTimeUtils.java

* #2288 Rename HOCurreny->AmountOfMoney

* #2290 Fix MatchFixtures.findReplacementOfTeam (#2291)

* #2292 Fix MatchLineupTeam.examineSubstitution

* #2292 Fix MatchLineupTeam.examineSubstitution

* #2292 Review: Remove unused method

* #2292 release_notes.md

* #2292 release_notes.md

* #2288 Add estonian language

* #2288 wip

* #2288 wip

* #2294 Fix array index out of bound exception in player overview (#2295)

* release_notes.md

* #2294 Fix array index out  of bound exception in player overview

* #2294 Fix array index out  of bound exception in player overview

* #2288 NoClassDefFoundError

* #2288 AmountOfMoney stored as Decimal

* #2288 AmountOfMoney stored as Decimal

* #2288 AmountOfMoney stored as Decimal DBUpdater

* #2288 combo  box selection in settings

* #2288 combo  box selection in settings

* #2288 Store currency settings

* #2288 documentation

* #2288 review

* #2288 review

* release HO 9.1 (#2300)

* Readme link to release HO 9.1

---------

Co-authored-by: Sébastien Le Callonnec <sebastien@weblogism.com>